### ISSUE TITLE
容器重新创建后 无法使用快速登录

### ISSUE THREAD

**Issue by 502647092** [NapNeko/NapCat-Docker#11]
尝试过持久化 /root/.config 目录 并没什么用
请问如何持久化设备信息和登录信息

**Comment by MliKiowa** [comment]
这是docker 创建虚拟或者隔离设备出现了变化，请翻阅 Docker 资料与文档

**Comment by 502647092** [comment]
通过持久化 `/root/.config` 并且固定容器 Mac地址之后 可以做到重启容器保持登录状态

**Comment by 502647092** [comment]
拉取最新的镜像后 之前的方案无法快捷登录 从手机上看是读取的之前的设备信息 并不是新的设备 应该是快捷登录流程用到了其他文件?

**Comment by 502647092** [comment]
docker diff 看到的文件变更
![image](https://github.com/NapNeko/NapCat-Docker/assets/10203793/17eb1a1c-d909-416d-9b05-1f90de93dcca)
已经持久化的文件信息
![image](https://github.com/NapNeko/NapCat-Docker/assets/10203793/e73b2986-e719-4081-ae5e-098609bfeb9a)

**Comment by MliKiowa** [comment]
和原来一样 你可以试试清掉镜像 重新试试

**Comment by duo** [comment]
目前的镜像, volume 得映射到 /root/.config/QQ 了, 参见 https://github.com/NapNeko/NapCat-Docker/commit/c934e2dd45dfbe82a73b15c198f77b11c0590cbe 的变更

**Comment by shanyan-wcx** [comment]
映射了/root/.config/QQ，也固定了MAC地址，还是无法持久化登录，设备信息还是会变。
