### ISSUE TITLE
docker报错

### ISSUE THREAD

**Issue by 1302557841** [NapNeko/NapCat-Docker#15]
[BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly.
[NativeCrashHandler.cpp][getStringList][280]!!!! getChar:NATIVE_RQD_REPORT, size:17.
[NativeCrashHandler.cpp][getStringList][280]!!!! getChar:rqd_rv, size:6.
[NativeCrashHandler.cpp][getStringList][280]!!!! getChar:1.0, size:3.
[NativeCrashHandler.cpp][parseCrashDetailBean][84]no intStateStr
[NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!
但是可以正常连接，工作几小时后会自动掉线

**Comment by initialencounter** [comment]
请提供完整日志，详细的平台信息，docker镜像sha256

**Comment by 1302557841** [comment]
Debian 11 docker 最新版本

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c3dd000-7fa42c3f6000 r-xp 0000c000 08:02 6553831                    /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c3f6000-7fa42c405000 r--p 00025000 08:02 6553831                    /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c405000-7fa42c406000 ---p 00034000 08:02 6553831                    /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c406000-7fa42c407000 r--p 00034000 08:02 6553831                    /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c407000-7fa42c409000 rw-p 00035000 08:02 6553831                    /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c409000-7fa42c414000 r--p 00000000 08:02 6553829                    /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.23609.1

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c414000-7fa42c423000 r-xp 0000b000 08:02 6553829                    /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.23609.1

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c423000-7fa42c42f000 r--p 0001a000 08:02 6553829                    /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.23609.1

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c42f000-7fa42c432000 r--p 00025000 08:02 6553829                    /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.23609.1

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c432000-7fa42c433000 rw-p 00028000 08:02 6553829                    /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.23609.1

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c435000-7fa42c440000 r--p 00000000 08:02 6553907                    /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.19.13

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c440000-7fa42c46e000 r-xp 0000b000 08:02 6553907                    /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.19.13

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c46e000-7fa42c480000 r--p 00039000 08:02 6553907                    /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.19.13

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c480000-7fa42c481000 ---p 0004b000 08:02 6553907                    /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.19.13

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c481000-7fa42c482000 r--p 0004b000 08:02 6553907                    /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.19.13

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c482000-7fa42c483000 rw-p 0004c000 08:02 6553907                    /usr/lib/x86_64-linux-gnu/libdbus-1.so.3.19.13

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c483000-7fa42c48e000 r--p 00000000 08:02 6591433                    /usr/lib/x86_64-linux-gnu/libnspr4.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c48e000-7fa42c4b0000 r-xp 0000b000 08:02 6591433                    /usr/lib/x86_64-linux-gnu/libnspr4.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c4b0000-7fa42c4be000 r--p 0002d000 08:02 6591433                    /usr/lib/x86_64-linux-gnu/libnspr4.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c4be000-7fa42c4bf000 r--p 0003a000 08:02 6591433                    /usr/lib/x86_64-linux-gnu/libnspr4.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c4bf000-7fa42c4c0000 rw-p 0003b000 08:02 6591433                    /usr/lib/x86_64-linux-gnu/libnspr4.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c4c3000-7fa42c4cb000 r--p 00000000 08:02 6591546                    /usr/lib/x86_64-linux-gnu/libsmime3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c4cb000-7fa42c4e3000 r-xp 00008000 08:02 6591546                    /usr/lib/x86_64-linux-gnu/libsmime3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c4e3000-7fa42c4e9000 r--p 00020000 08:02 6591546                    /usr/lib/x86_64-linux-gnu/libsmime3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c4e9000-7fa42c4ec000 r--p 00025000 08:02 6591546                    /usr/lib/x86_64-linux-gnu/libsmime3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c4ec000-7fa42c4ed000 rw-p 00028000 08:02 6591546                    /usr/lib/x86_64-linux-gnu/libsmime3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c4ed000-7fa42c4f9000 r--p 00000000 08:02 6591438                    /usr/lib/x86_64-linux-gnu/libnssutil3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c4f9000-7fa42c50b000 r-xp 0000c000 08:02 6591438                    /usr/lib/x86_64-linux-gnu/libnssutil3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c50b000-7fa42c517000 r--p 0001e000 08:02 6591438                    /usr/lib/x86_64-linux-gnu/libnssutil3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c517000-7fa42c518000 ---p 0002a000 08:02 6591438                    /usr/lib/x86_64-linux-gnu/libnssutil3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c518000-7fa42c51f000 r--p 0002a000 08:02 6591438                    /usr/lib/x86_64-linux-gnu/libnssutil3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c51f000-7fa42c520000 rw-p 00031000 08:02 6591438                    /usr/lib/x86_64-linux-gnu/libnssutil3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c520000-7fa42c538000 r--p 00000000 08:02 6591434                    /usr/lib/x86_64-linux-gnu/libnss3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c538000-7fa42c615000 r-xp 00018000 08:02 6591434                    /usr/lib/x86_64-linux-gnu/libnss3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c615000-7fa42c648000 r--p 000f5000 08:02 6591434                    /usr/lib/x86_64-linux-gnu/libnss3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c648000-7fa42c64e000 r--p 00127000 08:02 6591434                    /usr/lib/x86_64-linux-gnu/libnss3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c64e000-7fa42c650000 rw-p 0012d000 08:02 6591434                    /usr/lib/x86_64-linux-gnu/libnss3.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c651000-7fa42c689000 r--p 00000000 08:02 6591305                    /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c689000-7fa42c79a000 r-xp 00038000 08:02 6591305                    /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c79a000-7fa42c81f000 r--p 00149000 08:02 6591305                    /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c81f000-7fa42c827000 r--p 001cd000 08:02 6591305                    /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c827000-7fa42c828000 rw-p 001d5000 08:02 6591305                    /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c82c000-7fa42c83b000 r--p 00000000 08:02 6591339                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c83b000-7fa42c86e000 r-xp 0000f000 08:02 6591339                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c86e000-7fa42c888000 r--p 00042000 08:02 6591339                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c888000-7fa42c88b000 r--p 0005b000 08:02 6591339                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c88b000-7fa42c88c000 rw-p 0005e000 08:02 6591339                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c88c000-7fa42c8a9000 r--p 00000000 08:02 6591327                    /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c8a9000-7fa42c938000 r-xp 0001d000 08:02 6591327                    /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c938000-7fa42c9c2000 r--p 000ac000 08:02 6591327                    /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9c2000-7fa42c9c3000 ---p 00136000 08:02 6591327                    /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9c3000-7fa42c9c4000 r--p 00136000 08:02 6591327                    /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9c4000-7fa42c9c5000 rw-p 00137000 08:02 6591327                    /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7200.4

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9c6000-7fa42c9c7000 r--p 00000000 08:02 5287448                    /usr/lib/x86_64-linux-gnu/libpthread.so.0

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9c7000-7fa42c9c8000 r-xp 00001000 08:02 5287448                    /usr/lib/x86_64-linux-gnu/libpthread.so.0

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9c8000-7fa42c9c9000 r--p 00002000 08:02 5287448                    /usr/lib/x86_64-linux-gnu/libpthread.so.0

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9c9000-7fa42c9ca000 r--p 00002000 08:02 5287448                    /usr/lib/x86_64-linux-gnu/libpthread.so.0

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9ca000-7fa42c9cb000 rw-p 00003000 08:02 5287448                    /usr/lib/x86_64-linux-gnu/libpthread.so.0

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9cb000-7fa42c9cc000 r--p 00000000 08:02 5287367                    /usr/lib/x86_64-linux-gnu/libdl.so.2

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9cc000-7fa42c9cd000 r-xp 00001000 08:02 5287367                    /usr/lib/x86_64-linux-gnu/libdl.so.2

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9cd000-7fa42c9ce000 r--p 00002000 08:02 5287367                    /usr/lib/x86_64-linux-gnu/libdl.so.2

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9ce000-7fa42c9cf000 r--p 00002000 08:02 5287367                    /usr/lib/x86_64-linux-gnu/libdl.so.2

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9cf000-7fa42c9d0000 rw-p 00003000 08:02 5287367                    /usr/lib/x86_64-linux-gnu/libdl.so.2

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42c9d6000-7fa42ca59000 r--p 00000000 08:02 5551228                    /opt/QQ/libffmpeg.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42ca59000-7fa42cc5e000 r-xp 00082000 08:02 5551228                    /opt/QQ/libffmpeg.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42cc5e000-7fa42cc83000 r--p 00286000 08:02 5551228                    /opt/QQ/libffmpeg.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42cc83000-7fa42cc84000 rw-p 002aa000 08:02 5551228                    /opt/QQ/libffmpeg.so

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42d126000-7fa42d128000 r--p 00000000 08:02 5287335                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42d128000-7fa42d152000 r-xp 00002000 08:02 5287335                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42d152000-7fa42d15d000 r--p 0002c000 08:02 5287335                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42d15e000-7fa42d160000 r--p 00037000 08:02 5287335                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fa42d160000-7fa42d162000 rw-p 00039000 08:02 5287335                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fffae106000-7fffae127000 rw-p 00000000 00:00 0                          [stack]

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fffae1a7000-7fffae1ab000 r--p 00000000 00:00 0                          [vvar]

[map_info_parser.c][parseXMapsLine][30]Parsing line: 7fffae1ab000-7fffae1ad000 r-xp 00000000 00:00 0                          [vdso]

 235,0000,phdr->p_offset = (nil), phdr->p_vaddr = (nil)
[backtrace.c][backtraceStackWithLibUnwind][273]Got unwind context.
in twice crash handler!
 235,0002,Initialization of unwind finished.
[backtrace.c][backtraceStackWithLibUnwind][308]pc = 0x7fa399e711d9, sp = 0x7fffae124f30
 235,0003,Try to search symbol info for pc: 0x7fa399e711d9
[BuglyService.cpp][buglySignalHandler][460]buglySignalHandler info=0x7fa38ade3830 context=0x7fa38ade3700 crashed=1 signal=11
2024-05-07 00:09:44,150 INFO reaped unknown pid 8 (exit status 1)

**Comment by MliKiowa** [comment]
试试最新版本
