### ISSUE TITLE
重新创建容器后无法运行

### ISSUE THREAD

**Issue by Henvy-Mango** [NapNeko/NapCat-Docker#18]
[entrypoint.sh](https://github.com/NapNeko/NapCat-Docker/blob/main/entrypoint.sh) 这里的逻辑需要修改一下，挂载了配置文件后，重新创建容器是不会重新解压napcat的，找不到可执行文件，报错`napcat  | entrypoint.sh: line 78: ./napcat.sh: No such file or directory`

```sh
if [ ! -f "$CONFIG_PATH" ]; then
    # 安装 napcat
    rarch=$(arch | sed s/aarch64/arm64/ | sed s/x86_64/x64/)
    unzip NapCat.linux.${rarch}.zip -d .
    mv NapCat.linux.${rarch} napcat
    chmod +x napcat/napcat.sh
```

**Comment by MliKiowa** [comment]
提个pr吧

**Comment by Henvy-Mango** [comment]
> 提个pr吧

我倾向于把解压这步骤放到 Dockerfile 里，你觉得呢

**Comment by MliKiowa** [comment]
我觉得是是这样

**Comment by MliKiowa** [comment]
但是最近才移出来

**Comment by initialencounter** [comment]
> 我倾向于把解压这步骤放到 Dockerfile 里
这是为了应对挂载空目录的情况
