### ISSUE TITLE
Docker 镜像时区错误

### ISSUE THREAD

**Issue by wling-art** [NapNeko/NapCat-Docker#20]
![image](https://github.com/NapNeko/NapCat-Docker/assets/90316914/538928c1-39d4-4592-bfee-f300e90e2e44)
在这里新建容器却是UTC +0，我希望他是UTC +8

**Comment by initialencounter** [comment]
这个是可以在创建容器时自己设置的哦

**Comment by wling-art** [comment]
> 这个是可以在创建容器时自己设置的哦

我设置了TZ=Asia/Shanghai环境变量但看起来没用？

**Comment by initialencounter** [comment]
> TZ=Asia/Shanghai

可能是因为没安装tzdata
试试用这个方法吧

docker run -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro

**Comment by wling-art** [comment]
> tzdata

还是没有用
主机时区：
![image](https://github.com/NapNeko/NapCat-Docker/assets/90316914/e3430222-ebe8-443e-8b3d-00a2160941f8)

容器时区：
![image](https://github.com/NapNeko/NapCat-Docker/assets/90316914/9e9c94a1-38fa-45e2-a299-0719b6532c3a)

完整的run指令
![image](https://github.com/NapNeko/NapCat-Docker/assets/90316914/d648d6d3-f55a-4646-887b-333ab9509690)

**Comment by initialencounter** [comment]
这个是同步你宿主机的时区，宿主机可能没改

**Comment by wling-art** [comment]
> ![image](https://private-user-images.githubusercontent.com/109729945/341833545-d8775934-1c0a-482b-8ae4-7776c5453218.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODg4MDcsIm5iZiI6MTcxODk4ODUwNywicGF0aCI6Ii8xMDk3Mjk5NDUvMzQxODMzNTQ1LWQ4Nzc1OTM0LTFjMGEtNDgyYi04YWU0LTc3NzZjNTQ1MzIxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxNjQ4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGIxYTJjMzYyMTI1NTg0MjIxZTlmZmY3OGFjYWMxMGY3ODUwM2I0ZGI4MGMzNGI2N2NmN2ViYWMzODYyMmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HiZje7f1A54TS1GXdHJnubW0pYoMSUF4JnCvj7XxWOc) 这个环境变量去掉

噢这个成功了谢谢，十分感谢
