### ISSUE TITLE
消息发送失败日志发送到QQ前端，随后过一会账号冻结24小时提示第三方修改

### ISSUE THREAD

**Issue by mmmjie** [NapNeko/NapCat-Docker#21]
不确定前后是否有关联，但这个报错是否应该记录在log文件里，而不是发送到QQ前端？
有时候一些群里的群员对着这条消息举报，太容易被冻结了

docker是昨天开始使用的，使用docker的np后，就没有使用其他适配器了

log文字版
E: ActionFailed(status='failed', retcode=1200, data=None, message="Error: ENOENT: no such file or directory, unlink '/root/.config/QQ/nt_qq_ce644ac606745a6cfd8dd18d9f1006c1/nt_data/Pic/2024-06/Ori/9ee1c95938a7c9b6d4124473aafaa37b.jpg'\n    at Object.unlinkSync (node:fs:1883:3)\n    at file:///usr/src/app/napcat/napcat.mjs:26264:47\n    at Array.map (<anonymous>)\n    at sendMsg (file:///usr/src/app/napcat/napcat.mjs:26264:24)\n    at async SendMsg._handle (file:///usr/src/app/napcat/napcat.mjs:26344:23)\n    at async SendMsg.websocketHandle (file:///usr/src/app/napcat/napcat.mjs:25782:23)\n    at async ReverseWebsocket.onmessage (file:///usr/src/app/napcat/napcat.mjs:30695:28)\n    at async WebSocket.<anonymous> (file:///usr/src/app/napcat/napcat.mjs:30734:7)", wording="Error: ENOENT: no such file or directory, unlink '/root/.config/QQ/nt_qq_ce644ac606745a6cfd8dd18d9f1006c1/nt_data/Pic/2024-06/Ori/9ee1c95938a7c9b6d4124473aafaa37b.jpg'\n    at Object.unlinkSync (node:fs:1883:3)\n    at file:///usr/src/app/napcat/napcat.mjs:26264:47\n    at Array.map (<anonymous>)\n    at sendMsg (file:///usr/src/app/napcat/napcat.mjs:26264:24)\n    at async SendMsg._handle (file:///usr/src/app/napcat/napcat.mjs:26344:23)\n    at async SendMsg.websocketHandle (file:///usr/src/app/napcat/napcat.mjs:25782:23)\n    at async ReverseWebsocket.onmessage (file:///usr/src/app/napcat/napcat.mjs:30695:28)\n    at async WebSocket.<anonymous> (file:///usr/src/app/napcat/napcat.mjs:30734:7)", echo='6486')
消息发送失败！

![image](https://github.com/NapNeko/NapCat-Docker/assets/45615222/587d6116-cf79-4c5b-b46d-db469e873ebe)
![image](https://github.com/NapNeko/NapCat-Docker/assets/45615222/53888c0c-2d13-4a93-8b31-25888b7bd976)

**Comment by MliKiowa** [comment]
被举报了吧

**Comment by mmmjie** [comment]
> 被举报了吧

估计是，主要有点奇怪这个LOG怎么会发到QQ前端

**Comment by MliKiowa** [comment]
这是你bot的逻辑

**Comment by mmmjie** [comment]
> 这是你bot的逻辑

这样吗，不好意思哦
