### ISSUE TITLE
napcat镜像构建失败

### ISSUE THREAD

**Issue by BBOY2024** [NapNeko/NapCat-Docker#26]
napcat镜像构建失败，使用aliyun和github action都部署，都出现了问题,问题如下 
`error: failed to solve: mlikiowa/napcat-docker:base: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/mlikiowa/napcat-docker/manifests/sha256:94e0ed1ba1a1249d1b2f9fbdd1146d5a3263c57fe4cd53c7856532d43a556969: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
93Build artifact registry.cn-hangzhou.aliyuncs.com/XXXX fail: "exit status 1"
94[build failed, takes 5s.]`

**Comment by MliKiowa** [comment]
检查网络

**Comment by Meliodas-gpu** [comment]
怎么解决的？
