### ISSUE TITLE
链接挂了

### ISSUE THREAD

**Issue by W1ndys** [NapNeko/NapCat-Docker#34]
![Screenshot_2024-09-04-10-41-18-725_com microsoft emmx-edit](https://github.com/user-attachments/assets/2012f277-4b1a-4553-a456-6ee3b972accc)
![Screenshot_2024-09-04-10-41-16-603_com microsoft emmx](https://github.com/user-attachments/assets/90446946-78da-4102-bc78-f2be36fc094e)

**Comment by MliKiowa** [comment]
哦 这个挂了不影响
