### ISSUE TITLE
docker映射配置相关问题

### ISSUE THREAD

**Issue by Windsland52** [NapNeko/NapCat-Docker#37]
napcat log：
```
发生错误 Error: ENOENT: no such file or directory, copyfile '/home/ubuntu/zhenxun_bot/resources/image/zai/4.jpg' -> '/app/.config/QQ/NapCat/temp/b8182155-57d4-470b-be0e-c1d3f3f44e61.jpg'
    at Object.copyFileSync (node:fs:3013:11)
    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)
    at uri2local (file:///app/napcat/napcat.mjs:5621:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:30012:9)
    at async Object.image (file:///app/napcat/napcat.mjs:29699:10)
    at async Promise.all (index 0)
    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:29957:17)
    at async SendMsg._handle (file:///app/napcat/napcat.mjs:36729:52)
    at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36629:23)
```
docker运行命令
```
docker run -d \
-e ACCOUNT=********** \
-e WSR_ENABLE=true \
-e WS_URLS='["ws://**.***.**.***:8080/onebot/v11/ws"]' \
-e NAPCAT_GID=0 \
-e NAPCAT_UID=0 \
--name napcat \
--restart=always \
mlikiowa/napcat-docker:latest
```

**Comment by MliKiowa** [comment]
你需要挂载zhenxun的目录

**Comment by Windsland52** [comment]
> 你需要挂载zhenxun的目录
```
发生错误 Error: ENOENT: no such file or directory, copyfile '/home/ubuntu/zhenxun_bot/resources/image/SIMPLE_HELP.png' -> '/app/.config/QQ/NapCat/temp/0cc10cb7-2eff-4fa0-94de-371f202a2313.png'
    at Object.copyFileSync (node:fs:3013:11)
    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)
    at uri2local (file:///app/napcat/napcat.mjs:5621:10)
    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:30012:9)
    at async Object.image (file:///app/napcat/napcat.mjs:29699:10)
    at async Promise.all (index 0)
    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:29957:17)
    at async SendMsg._handle (file:///app/napcat/napcat.mjs:36729:52)
    at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36629:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12815:21) 
```
```
发生错误 Error: ENOENT: no such file or directory, copyfile '/home/ubuntu/zhenxun_bot/data/group_help/709682480.png' -> '/app/.config/QQ/NapCat/temp/31f3d428-2273-41a1-8ea0-c5bfb0ab6d63.png'
    at Object.copyFileSync (node:fs:3013:11)
    at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)
    at uri2local (file:///app/napcat/napcat.mjs:5621:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:30012:9)
    at async Object.image (file:///app/napcat/napcat.mjs:29699:10)
    at async Promise.all (index 0)
    at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:29957:17)
    at async SendMsg._handle (file:///app/napcat/napcat.mjs:36729:52)
    at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36629:23) 
```
主要想问下这种两个目录都需要挂载的情况该怎么办，直接挂载/home/ubuntu/zhenxun_bot/到/app/.config/QQ/NapCat/temp也不行

**Comment by Windsland52** [comment]
> > 你需要挂载zhenxun的目录
> 
> ```
> 发生错误 Error: ENOENT: no such file or directory, copyfile '/home/ubuntu/zhenxun_bot/resources/image/SIMPLE_HELP.png' -> '/app/.config/QQ/NapCat/temp/0cc10cb7-2eff-4fa0-94de-371f202a2313.png'
>     at Object.copyFileSync (node:fs:3013:11)
>     at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)
>     at uri2local (file:///app/napcat/napcat.mjs:5621:10)
>     at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:30012:9)
>     at async Object.image (file:///app/napcat/napcat.mjs:29699:10)
>     at async Promise.all (index 0)
>     at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:29957:17)
>     at async SendMsg._handle (file:///app/napcat/napcat.mjs:36729:52)
>     at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36629:23)
>     at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12815:21) 
> ```
> 
> ```
> 发生错误 Error: ENOENT: no such file or directory, copyfile '/home/ubuntu/zhenxun_bot/data/group_help/709682480.png' -> '/app/.config/QQ/NapCat/temp/31f3d428-2273-41a1-8ea0-c5bfb0ab6d63.png'
>     at Object.copyFileSync (node:fs:3013:11)
>     at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)
>     at uri2local (file:///app/napcat/napcat.mjs:5621:10)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:30012:9)
>     at async Object.image (file:///app/napcat/napcat.mjs:29699:10)
>     at async Promise.all (index 0)
>     at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:29957:17)
>     at async SendMsg._handle (file:///app/napcat/napcat.mjs:36729:52)
>     at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36629:23) 
> ```
> 
> 主要想问下这种两个目录都需要挂载的情况该怎么办，直接挂载/home/ubuntu/zhenxun_bot/到/app/.config/QQ/NapCat/temp也不行

试了下
```
docker run -d \
-e ACCOUNT= \
-e WSR_ENABLE=true \
-e WS_URLS='["ws:///onebot/v11/ws"]' \
-e NAPCAT_GID=0 \
-e NAPCAT_UID=0 \
-v /home/ubuntu/zhenxun_bot/resources/image:/app/.config/QQ/NapCat/temp \
--name napcat \
--restart=always \
mlikiowa/napcat-docker:latest
```
发现还是会报 `发生错误 Error: ENOENT: no such file or directory, copyfile '/home/ubuntu/zhenxun_bot/resources/image/SIMPLE_HELP.png' -> '/app/.config/QQ/NapCat/temp/ee3e8b82-0602-4ac9-ad27-1ee403d6e11a.png'` 是挂载方式错了吗

**Comment by Windsland52** [comment]
> > > 你需要挂载zhenxun的目录
> > 
> > 
> > ```
> > 发生错误 Error: ENOENT: no such file or directory, copyfile '/home/ubuntu/zhenxun_bot/resources/image/SIMPLE_HELP.png' -> '/app/.config/QQ/NapCat/temp/0cc10cb7-2eff-4fa0-94de-371f202a2313.png'
> >     at Object.copyFileSync (node:fs:3013:11)
> >     at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)
> >     at uri2local (file:///app/napcat/napcat.mjs:5621:10)
> >     at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:30012:9)
> >     at async Object.image (file:///app/napcat/napcat.mjs:29699:10)
> >     at async Promise.all (index 0)
> >     at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:29957:17)
> >     at async SendMsg._handle (file:///app/napcat/napcat.mjs:36729:52)
> >     at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36629:23)
> >     at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:12815:21) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 发生错误 Error: ENOENT: no such file or directory, copyfile '/home/ubuntu/zhenxun_bot/data/group_help/709682480.png' -> '/app/.config/QQ/NapCat/temp/31f3d428-2273-41a1-8ea0-c5bfb0ab6d63.png'
> >     at Object.copyFileSync (node:fs:3013:11)
> >     at Object.func [as copyFileSync] (node:electron/js2c/node_init:2:3119)
> >     at uri2local (file:///app/napcat/napcat.mjs:5621:10)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> >     at async OneBotMsgApi.handleOb11FileLikeMessage (file:///app/napcat/napcat.mjs:30012:9)
> >     at async Object.image (file:///app/napcat/napcat.mjs:29699:10)
> >     at async Promise.all (index 0)
> >     at async OneBotMsgApi.createSendElements (file:///app/napcat/napcat.mjs:29957:17)
> >     at async SendMsg._handle (file:///app/napcat/napcat.mjs:36729:52)
> >     at async SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:36629:23) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 主要想问下这种两个目录都需要挂载的情况该怎么办，直接挂载/home/ubuntu/zhenxun_bot/到/app/.config/QQ/NapCat/temp也不行
> 
> 试了下
> 
> ```
> docker run -d \
> -e ACCOUNT= \
> -e WSR_ENABLE=true \
> -e WS_URLS='["ws:///onebot/v11/ws"]' \
> -e NAPCAT_GID=0 \
> -e NAPCAT_UID=0 \
> -v /home/ubuntu/zhenxun_bot/resources/image:/app/.config/QQ/NapCat/temp \
> --name napcat \
> --restart=always \
> mlikiowa/napcat-docker:latest
> ```
> 
> 发现还是会报 `发生错误 Error: ENOENT: no such file or directory, copyfile '/home/ubuntu/zhenxun_bot/resources/image/SIMPLE_HELP.png' -> '/app/.config/QQ/NapCat/temp/ee3e8b82-0602-4ac9-ad27-1ee403d6e11a.png'` 是挂载方式错了吗

改成 `-v /home/ubuntu/zhenxun_bot/:/home/ubuntu/zhenxun_bot/` 就行了，蠢到我了，谢谢大佬。
