### ISSUE TITLE
重新创建容器后无法运行

### ISSUE THREAD

**Issue by dontKon** [NapNeko/NapCat-Docker#41]
第一次创建容器启动没有问题，再次创建容器后提示以下错误

bash: entrypoint.sh: No such file or directory

我的启动命令：
docker run -d \
-e ACCOUNT=*****\
-e WSR_ENABLE=true \
-e WS_URLS='["ws://http://******"]' \
-e NAPCAT_GID=$(id -g) \
-e NAPCAT_UID=$(id -u) \
-p 3101:3001 \
-p 6199:6099 \
-v /data/dev/listener:/app \
--name napcat2  \
--memory=512m \
--log-driver=json-file --log-opt max-size=1024m --log-opt max-file=5 \
--restart=always \
mlikiowa/napcat-docker:latest

**Comment by MliKiowa** [comment]
你映射的文件夹换一下目录

**Comment by MliKiowa** [comment]
> 映射容器内的app目录会导致无法启动，映射其他目录没有问题。
> 
> 如果我想把 QQ持久化和NapCat配置文件映射到宿主机该如何操作呢

运行后cv过去应该能行

**Comment by dontKon** [comment]
好的。看来这是唯一的办法了
