### ISSUE TITLE
Token 在哪里？

### ISSUE THREAD

**Issue by unsiao** [NapNeko/NapCat-Docker#45]
### 第一次 compose up -d 后没有token

**Comment by MliKiowa** [comment]
docker logs 容器名

**Comment by unsiao** [comment]
Okey!!!
________________________________
发件人: 手瓜一十雪 ***@***.***>
发送时间: 2024年11月28日 15:33
收件人: NapNeko/NapCat-Docker ***@***.***>
抄送: Shang ***@***.***>; Author ***@***.***>
主题: Re: [NapNeko/NapCat-Docker] Token 在哪里？ (Issue #45)


Closed #45<https://github.com/NapNeko/NapCat-Docker/issues/45> as completed.

―
