### ISSUE TITLE
扫码登录不了，容器打包的qq版本可以升级一下吗？

### ISSUE THREAD

**Issue by wdssfff00** [NapNeko/NapCat-Docker#47]
报错如下
![7844a808fb4354e694b2bf509d43f360](https://github.com/user-attachments/assets/7f117bb7-3c95-434f-bb0f-badfb8fcb994)
有相同错误用户说更新一下就好了
![image](https://github.com/user-attachments/assets/216cb238-12ed-42ce-825a-18bc2b4c83f1)
![image](https://github.com/user-attachments/assets/e2b2ab31-531e-4531-8e05-e03489313724)

可帮助测试喵~

**Comment by MliKiowa** [comment]
已更新到最新版

**Comment by chuyinluotian01** [comment]
今早部署了两个版本，一个登陆了没有问题，一个今天晚上就登不上去了，删除重新部署也不行，难受，
