### ISSUE TITLE
使用docker启动后，请求被重置

### ISSUE THREAD

**Issue by niusme** [NapNeko/NapCat-Docker#8]
# docker compose HTTP POST
version: "3"
services:
    napcat:
        environment:
            - ACCOUNT=<机器人qq>
            - HTTP_ENABLE=true
            - HTTP_POST_ENABLE=true
            - HTTP_URLS="http://192.168.3.8:5140/onebot"
        ports:
            - 3000:3000
        container_name: napcat
        network_mode: bridge
        image: mlikiowa/napcat-docker:latest
使用上述docker-compose启动后，

在宿主机上 发送
curl --request POST \
  --url http://127.0.0.1:3000/send_msg \
  --header 'Content-Type: application/json' \
  --header 'content-type: application/json' \
  --data '{
    "message_type":"private",
    "user_id": ******,
    "message":"早上好"
}'

返回：curl: (56) Recv failure: Connection reset by peer

麻烦作者大大看看

**Comment by MliKiowa** [comment]
docker不能用127.0.0.1直接访问

**Comment by niusme** [comment]
我使用  docker inspect 查看容器ip后，使用容器ip 172.17.0.2  

curl --request POST \
  --url http://172.17.0.2:3000/send_msg \
  --header 'Content-Type: application/json' \
  --header 'content-type: application/json' \
  --data '{
    "message_type":"private",
    "user_id": ******,
    "message":"早上好"
}'

返回
curl: (7) Failed to connect to 172.17.0.2 port 3000: Connection refused

**Comment by MliKiowa** [comment]
你应该看看容器内服务有没有正常启动 napcat启动时会输出你的配置 检查下

**Comment by initialencounter** [comment]
> version: "3" services: napcat: environment: - ACCOUNT=<机器人qq> - HTTP_ENABLE=true - HTTP_POST_ENABLE=true - HTTP_URLS="http://192.168.3.8:5140/onebot" ports: - 3000:3000 container_name: napcat network_mode: bridge image: mlikiowa/napcat-docker:latest 使用上述docker-compose启动后，

宿主机系统方、还有docker版本便提供一些吗？network_mode: host 试试呢

**Comment by niusme** [comment]
系统
![impicture_20240423_152838](https://github.com/NapNeko/NapCat-Docker/assets/58981284/bf85f87b-8c8e-4343-ba4f-fa718672a2ee)
docker 版本
![impicture_20240423_152918](https://github.com/NapNeko/NapCat-Docker/assets/58981284/51bd3435-8d75-4e9e-adb6-e426bd80848a)


默认网络配置可以看见3000端口被占用，改成host后 3000端口没有被占用。

**Comment by initialencounter** [comment]
> 默认网络配置可以看见3000端口被占用

把之前服务的用 docker compose down 删掉

**Comment by niusme** [comment]
之前操作是 down掉 再up的。

**Comment by initialencounter** [comment]
> 默认网络配置可以看见3000端口被占用，改成host后 3000端口没有被占用。

host模式下不需要映射端口了，现在可以访问到容器内的onebot服务了吗

**Comment by niusme** [comment]
![impicture_20240423_161601](https://github.com/NapNeko/NapCat-Docker/assets/58981284/95400a8b-23df-440c-9e6a-e7c6e79eb751)


![impicture_20240423_161530](https://github.com/NapNeko/NapCat-Docker/assets/58981284/5812cfb4-4b18-4bae-8ddc-fbc5070c3044)

**Comment by niusme** [comment]
而且这个时候 netstat -l 发现3000端口并没有被占用

**Comment by initialencounter** [comment]
> 而且这个时候 netstat -l 发现3000端口并没有被占用

不要 curl 回环地址，改成公网或内网IP

**Comment by initialencounter** [comment]
顺便看一下容器日志

**Comment by initialencounter** [comment]
似乎是配置未读取成功，目前docker-compose存在一些问题，修好了会跟你说

**Comment by initialencounter** [comment]
把那个url两边的双引号去掉就行了

**Comment by initialencounter** [comment]
![image](https://github.com/NapNeko/NapCat-Docker/assets/109729945/936d7bdd-d881-412b-a766-360ba71dda57)
 docker-compose 的双引号不会被转义
![image](https://github.com/NapNeko/NapCat-Docker/assets/109729945/4bc8ff49-3066-4fdb-90b2-9072d695b5e9)
读取配置的错误被catch掉了

**Comment by niusme** [comment]
去掉引号就可以啦 。
